name: myhelm-stack
services:
  backend:
    container_name: helm-container
    build: .
    ports:
      - "8080:8080"
    restart: always 
    depends_on:
      - mysql-db
    volumes:
      - ./uploads:/root/uploads
      - ./charts:/root/charts
    networks:
      - helmnet

  mysql-db:
    container_name: mydb
    image: mysql:8.0
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    networks:
      - helmnet
    environment:
      MYSQL_ROOT_PASSWORD: dbuser123
      MYSQL_DATABASE: helmTemplate

volumes:
  mysql_data:

networks:
  helmnet:
